#Makefile for Red Hat Documentation
#Created by Jeff Fearn <jfearn@redhat.com>
#Copyright Red Hat Inc. 2006

XML_LANG	= en-US
DOCNAME		= Seam_Reference_Guide
PRODUCT		= Seam_Framework
BRAND		= JBoss

TRANSLATIONS    = $(XML_LANG)
OTHER_LANGS    = as-IN bn-IN de-DE es-ES es-MX fr-FR gu-IN hi-IN it-IT ja-JP kn-IN ko-KR ml-IN mr-IN or-IN pa-IN pt-BR ru-RU si-LK sl-SL ta-IN te-IN zh-CN zh-TW
#TRANSLATIONS   = $(XML_LANG) $(OTHER_LANGS)

COMMON_CONFIG  = /usr/share/publican
include $(COMMON_CONFIG)/make/Makefile.common
